package com.userAdmin.dao.model.UserAdministration;
// Generated 14 Nov, 2015 3:14:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserDetails generated by hbm2java
 */
public class UserDetails  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String password;
     private String emailId;
     private Byte verified;
     private Set verificationTokens = new HashSet(0);

    public UserDetails() {
    }

    public UserDetails(String userName, String password, String emailId, Byte verified, Set verificationTokens) {
       this.userName = userName;
       this.password = password;
       this.emailId = emailId;
       this.verified = verified;
       this.verificationTokens = verificationTokens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public Byte getVerified() {
        return this.verified;
    }
    
    public void setVerified(Byte verified) {
        this.verified = verified;
    }
    public Set getVerificationTokens() {
        return this.verificationTokens;
    }
    
    public void setVerificationTokens(Set verificationTokens) {
        this.verificationTokens = verificationTokens;
    }

	@Override
	public String toString() {
		return "UserDetails [id=" + id + ", userName=" + userName
				+ ", password=" + password + ", emailId=" + emailId
				+ ", verified=" + verified + ", verificationTokens="
				+ verificationTokens + "]";
	}
    
    

}


